<!DOCTYPE html>
<html>
<head>
	<meta charset='utf-8'>
	<title>Miles Per Gallon Predictor</title>
	<meta name="description" content="Miles Per Gallon Predictor">
	<meta name="author" content="Sridhar Pilli">
	<meta name="generator" content="slidify" />
	
	<!-- LOAD STYLE SHEETS -->
	<link rel="stylesheet" href="libraries/frameworks/html5slides/default/styles.css">
	<link rel="stylesheet" href="libraries/highlighters/highlight.js/css/tomorrow.css" />  <link rel="stylesheet" href = "assets/css/ribbons.css">
  
</head>
<body style='display: none'>
	<section class='slides layout-regular template-regular'>
     <article class="" id="slide-1" style="background:;">
  <h3>Introduction</h3>
  <ul>
<li><p>MPG predictor is a shiny application that predicts the miles per gallon of a car given its</p>

<ul>
<li>Engine displacement in cu.in.</li>
<li>Transmission type - Automatic or Manual</li>
<li>The number of carburetors used.</li>
</ul></li>
<li><p>The actual prediction is carried out using a linear regression model fitted on the <strong>mtcars</strong> dataset from the datasets package in R</p></li>
</ul>

<pre><code class="r">head(mtcars,4)
</code></pre>

<pre><code>##                 mpg cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4      21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag  21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710     22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive 21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
</code></pre>

</article>

<article class="class" id="id" style="background:;">
  <h3>Fitted model and its summary</h3>
  <pre><code class="r">fit &lt;- lm(mpg ~ disp + am + carb ,mtcars)
summary(fit)
</code></pre>

<pre><code>## 
## Call:
## lm(formula = mpg ~ disp + am + carb, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.1034 -1.6113 -0.4638  1.6840  5.0685 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 28.17607    1.50009  18.783  &lt; 2e-16 ***
## disp        -0.02515    0.00558  -4.508 0.000106 ***
## am           3.80481    1.27529   2.983 0.005851 ** 
## carb        -1.36103    0.34587  -3.935 0.000500 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.628 on 28 degrees of freedom
## Multiple R-squared:  0.8283, Adjusted R-squared:  0.8099 
## F-statistic: 45.02 on 3 and 28 DF,  p-value: 7.691e-11
</code></pre>

</article>

<article class="" id="slide-3" style="background:;">
  <h3>Fitted model and its summary</h3>
  <ul>
<li>The R-squared is 80.99% indicating about 80% of the variance is captured by this model. </li>
<li>All the variables considered has statistically significant beta values in the model. Hence this is a reasonably good model.</li>
<li>Note that there is a negative association between engine displacement and mpg. As one increases, the other decreases.</li>
<li>Likewise there is a negative association between number of carburetors and mpg.</li>
<li>Overall manual cars have higher mpg than automatic transmission type cars.</li>
</ul>

</article>

<article class="" id="slide-4" style="background:;">
  <h3>App usage</h3>
  <ul>
<li>Select the Engine displacement on the slider bar</li>
<li>Select the Transmission type from the drop down menu</li>
<li><p>Enter or select the Number of carburetors.</p></li>
<li><p>The main panel on the righ displays the values entered, plots them and gives out the predicted mpg and its confidence interval.</p></li>
<li><p>Confidence interval is calculated using the 95% confidence assuimng a t-distribution for the predicted mpg.</p></li>
</ul>

</article>

<article class="" id="slide-5" style="background:;">
  <h3>Conclusion</h3>
  <ul>
<li>Overall the model seems to do a good job with a residual standard error of 2.628 on 28 degrees of freedom</li>
<li>The model predicts appropriate mpg as per the associations with various variables - displacement, transmission type and number of carburetors. For eg., By selecting a higher engine displacement a lower predicted mpg is generated. </li>
</ul>

</article>

<article class="" id="slide-6" style="background:;">
  <h3>Code</h3>
  <ul>
<li>ui.R can be found <a href="https://github.com/spilli/MPG_predictor/blob/master/ui.R">here</a></li>
<li>server.R can be found <a href="https://github.com/spilli/MPG_predictor/blob/master/server.R">here</a></li>
</ul>

</article>

  </section>
</body>
  <!-- LOAD JAVASCRIPTS  -->
	<script src='libraries/frameworks/html5slides/default/slides.js'></script>
	<!-- LOAD HIGHLIGHTER JS FILES -->
	<script src="libraries/highlighters/highlight.js/highlight.pack.js"></script>
	<script>hljs.initHighlightingOnLoad();</script>
	<!-- DONE LOADING HIGHLIGHTER JS FILES -->
	 
	</html>
